### ISSUE TITLE
Missing includes for common

### ISSUE THREAD

**Issue by kokarn** [reelyactive/advlib#1]
Hello!

I'll start off by saying I'm really impressed with the library here.

There does however seem to be some things missing. 
When trying to identify a manufacturer with the example from the readme `advlib.ble.common.companyidentifiercodes.companyNames['000d'];` it throws an error that common is not defined.

When looking at https://github.com/reelyactive/advlib/blob/master/lib/ble/index.js you can see identifiers defined but never exported. 

In fact, nothing is exported at all for common.

Is this by design or just an oversight? 
I've quickly looked over the source and most of the files seem to be there.

**Comment by jeffyactive** [comment]
Thanks @kokarn, you are indeed correct that the failure to export the BLE common resources was an oversight.  This has now been corrected in advlib@0.0.12.  You can now access all the `advlib.ble.common.xxx` resources given in the examples in the README.  We've also taken the time to update all the assigned numbers from the Bluetooth SIG.

Cheers from Canada!

**Comment by kokarn** [comment]
Wow, that was quick!

Thank you so much, will look into this tomorrow and hopefully everything should work as expected.

Cheers from Sweden!
