### ISSUE TITLE
Ignore case for uuid check

### ISSUE THREAD

**Issue by TheMysticMan** [reelyactive/advlib#3]
Thanks for this library, really helped me out:)

I ran into one problem:
In gatt/services/members/google.js you're checking on 'feaa'.
The uuid I get is 'FEAA' so it won't work because of the case difference.
Maybe you could make it case insensitive?

I now manually change the case and run the process method myself

**Comment by jeffyactive** [comment]
Thanks for raising this issue @TheMysticMan.  We've updated the main process() function to convert the input to lowercase as we assume that covers the majority of use cases.

In the case where one calls the process() function on a single element of the packet (ex: Eddystone), it is still necessary to convert to lowercase first.  Hope this is a reasonable compromise.

In the next major version, we're considering using Buffer in place of String which would avoid the ambiguity.  Glad this library helped you out!
