### ISSUE TITLE
gap undefined

### ISSUE THREAD

**Issue by rgstephens** [reelyactive/advlib#4]
Thanks for this library.  Works great except I can't directly process servicedata or other gap packets:

```
advlib.ble.data.gap.servicedata.process('4941414c72784741414c7359637754714f59493d', 0, {})
```

Returns `Cannot read property 'servicedata' of undefined`

**Comment by jeffyactive** [comment]
Thanks for the feedback @rgstephens which provided motivation to clean up and improve the GAP functionality and documentation.  As of v0.1.0 you can now call:
`advlib.ble.data.gap.servicedata.process('0a181204eb150000')`

where the parameter is just the service data (as a hexadecimal string) which will return:
    {
      serviceData: {
        uuid : "180a",
        data : "1204eb150000",
        specificationName: "Device Information"
      }
    }

as documented [here](https://github.com/reelyactive/advlib#service-data).

**Comment by rgstephens** [comment]
I found that it works if I call

```
advlib.ble.data.process(...
```

but that seems contrary to the docs.

**Comment by jeffyactive** [comment]
The use of advlib depends very much on what you're using as a source.  Our reelyActive reelceivers DON'T run the Bluetooth stack, and actually provide the entire BLE Packet Data Unit (PDU) which is what advlib processes when you use advlib.ble.process().

However, most platforms WON'T give you the entire PDU.  In this case, it makes sense to use only a specific part of advlib to process what you can actually access of the PDU.  The latest updates should make it easier to process, for instance, just a single GAP data type, which would imply using advlib.ble.data.process() as you suggest @rgstephens.

If you can elaborate on your data source, we can try to improve the docs to accommodate.  :-)
